### ISSUE TITLE
GPS error model

### ISSUE THREAD

**Issue by l0g1x** [tu-darmstadt-ros-pkg/hector_gazebo#17]
The GPS plugin is outputting 0's for all of its covariance values, which does not make it as close to a real world scenario as possible. Im using this plugin as a input into robot_localization, and trying to model the setup i have in gazebo, as close as i can to my real world robot. Is anybody planning on implementing some sort of error model into this soon?

https://github.com/tu-darmstadt-ros-pkg/hector_gazebo/blob/hydro-devel/hector_gazebo_plugins/src/gazebo_ros_gps.cpp#L227

**Comment by meyerj** [comment]
hector_gazebo_plugins already implements a first-order error model to simulate drift and Gaussian noise which is also applied to the simulated GNSS position and velocity. Only the `position_covariance` field in the output message was not filled. I committed a simple fix for that, but I have not tested it with robot_localization.

It also should be noted that since cb62f26a3263d1ee358f436020306526e9a92344 the error model does not start with zero error anymore but initializes the drift error from a Gaussian distribution according to the model parameters. This is especially important for the GPS plugin.

**Comment by skohlbr** [comment]
I merged this also into indigo-devel.
