### ISSUE TITLE
hector_gazebo_plugins IMU acceleration incorrect

### ISSUE THREAD

**Issue by adasta** [tu-darmstadt-ros-pkg/hector_gazebo#8]
The gravity vector out of the IMU is in the wrong direction.  If the Z axis of the IMU frame points up, then the published IMU message reads accelerations of [0,0,9.81].

Why is gravity subtracted in the plugin?
https://github.com/tu-darmstadt-ros-pkg/hector_gazebo/blob/hydro-devel/hector_gazebo_plugins/src/gazebo_ros_imu.cpp#L249

**Comment by adasta** [comment]
I believe this commit fixes the problem : https://github.com/adasta/hector_gazebo/commit/f91d510e9b9a55c6e678117fade3f4e7e4c9f368

I am testing it on Ubuntu 12.04 and ROS Hydro.

**Comment by meyerj** [comment]
Hi adasta,

it is a matter of definition: The IMU measures the displacement of a probe mass, which indeed is accelerated downwards (or negative z depending on the orientation of the coordinate system). But if you consider the accelerometer as a device that measures the acceleration of the body it is attached to relative to an inertial reference coordinate system, gravity and acceleration towards the positive z axis have the same effect. This is how the values given by gazebo_ros_imu should be interpreted.

If you want to add gravity instead of subtracting, you also have to invert the sign of the acceleration that corresponds to a change of velocity. Otherwise you would not simulate a real accelerometer.

**Comment by adasta** [comment]
Thank you for the explanation!  I did not consider an alternate convention and had just thought it was a some regression in an external interface.
