### ISSUE TITLE
ros_imu orientation return null

### ISSUE THREAD

**Issue by olmerg** [tu-darmstadt-ros-pkg/hector_gazebo#9]
Sometimes the orientation quaternion return null ,the plugin p3d never generate this problem

**Comment by meyerj** [comment]
I cannot reproduce the problem. Do you have some more information about when exactly this happens or steps how to reproduce the problems? Which configuration values are you using for the plugin in your robot model?

Also note that the hector_gazebo IMU plugin has a different purpose than the P3D plugin in the [gazebo_plugins](http://wiki.ros.org/gazebo_plugins) package. It simulates an IMU/AHRS device and the resulting orientation error due to accelerometer biases is not just a constant offset from the ground truth orientation as in the P3D plugin. However, if the offset/drift/noise parameters are set to their default values (no errors), the resulting IMU orientation should be a perfect ground truth.

**Comment by meyerj** [comment]
This might be related to #12. Which parameters are use using for drift and noise?

**Comment by olmerg** [comment]
it is the problem. solved!!
